### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
	"email": "example@example.com",
	"password": "123456"
}

### Find a specific user with a given id
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth/?email=example@example.com

### Remove a specific user with a given id
DELETE http://localhost:3000/auth/1